name: deploy-container

# On property designates when we want to run this workflow or what events are we watching for
on:
  push:
    # We are going to watch for push event only on the branch master
    branches:
      - master
    # paths: we'll only run this workflow when we make a change specifically to the container folder
    paths:
      - 'packages/container/**'
# This is going to set the execusion environment to inside of our container directory, running npm install, npm build
defaults:
  run:
    working-directory: packages/container

jobs:
  # build is going to build and deploy our project
  build:
    # ubuntu-latest is one of the virtual machine created by github
    runs-on: ubuntu-latest
    # steps is where the commands that we want to run
    steps:
      # First step is to checkout the code we've witten in the virtual machine
      # Second is installing dependencies and create a production build using webpack
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
        env:
          PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}

      # Deploy to AWS, using aws-cli which gives us programatic access to AWS
      # Get access to the cli we use the next property
      - uses: shinyinc/action-aws-cli@v1.2
      # Then we use the cli to run a command
      # aws to reach to the s3 feature inside the cli and then sync the dist directory that was created with an s3 bucket
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{  secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{  secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/container/latest/index.html"
        env:
          AWS_ACCESS_KEY_ID: ${{  secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{  secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
